
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gyana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyana
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
        - name: gyana
          image: gyanaswain09634/ansibel-jenkins
          imagePullPolicy: Always
          ports:
            - containerPort: 80
